apiVersion: v1
kind: PersistentVolume
metadata:
  name: joke-db-volume
  labels:
    type: local
spec:
  storageClassName: manual2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/joke-volume"
