apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joke-db-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName: manual2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
