apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-db
spec:
  selector:
    matchLabels:
      app: joke-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joke-db
    spec:
      containers:
        - image: mysql:latest
          name: joke-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: joke-db
          volumeMounts:
            - name: joke-db-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: joke-db-persistent-storage
          persistentVolumeClaim:
            claimName: joke-db-pv-claim

